version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  notification-service:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - rabbitmq